# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleanup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('image', models.CharField(max_length=300)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanups', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('cross_street', models.CharField(max_length=100)),
                ('city', models.CharField(default='Oakland', max_length=100)),
                ('state', models.CharField(default='California', max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('cleanups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanups.Cleanup')),
            ],
        ),
    ]
