# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='cleanups',
        ),
        migrations.AddField(
            model_name='cleanup',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanups.Location'),
            preserve_default=False,
        ),
    ]
