# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0003_auto_20171126_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleanup',
            old_name='name',
            new_name='title',
        ),
    ]
