# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0004_auto_20171215_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanup',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
