# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0005_cleanup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('intersection', 'Intersection'), ('address', 'Address'), ('premise', 'Public Building'), ('landmark', 'Landmark')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
