# Generated by Django 2.0.2 on 2018-02-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0006_auto_20171228_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanup',
            name='image',
            field=models.CharField(blank=True, default='images/defaults/bow_rake.jpg', max_length=300),
        ),
    ]
