# Generated by Django 2.0.2 on 2018-05-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0007_auto_20180214_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('cleanup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanups.Cleanup')),
            ],
            options={
                'verbose_name_plural': 'required tools',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('image_static_location', models.CharField(blank=True, max_length=200)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'tool categories',
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cleanups.ToolCategory'),
        ),
        migrations.AddField(
            model_name='requiredtool',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanups.Tool'),
        ),
        migrations.AddField(
            model_name='cleanup',
            name='required_tools',
            field=models.ManyToManyField(through='cleanups.RequiredTool', to='cleanups.Tool'),
        ),
        migrations.AlterUniqueTogether(
            name='requiredtool',
            unique_together={('tool', 'cleanup')},
        ),
    ]
