# Generated by Django 2.0.2 on 2018-05-03 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0008_auto_20180503_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleanup',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cleanup',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='cleanup',
            name='start_time',
        ),
        migrations.AddField(
            model_name='cleanup',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanup',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='query',
            field=models.CharField(blank=True, help_text='String used to query this location', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleanups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(blank=True, choices=[('intersection', 'Intersection'), ('address', 'Address'), ('premise', 'Public Building'), ('landmark', 'Landmark')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
